sudo: required
dist: xenial
before_install:
- sudo apt-get -qq update && sudo apt-get install -y fonts-inconsolata texlive-full texlive-fonts-recommended 
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
  texlive-font-utils texlive-full graphviz fonts-font-awesome texlive-fonts-extra texlive-math-extra texlive-lang-english texlive-latex-extra texlive-xetex
- sudo fc-cache -fv
- fc-cache -vf 
script:
- make